/*
    Student ID: 1155077469
    Name: Choi Man Kin
*/

/* Query 1 */
SELECT
  LID,
  LEAGUE_NAME,
  SEASON,
  TEAM_NAME
FROM LEAGUES
  LEFT JOIN TEAMS ON LEAGUES.CHAMPION_TID = TEAMS.TID
WHERE TEAMS.AVERAGE_AGE = (SELECT MIN(AVERAGE_AGE)
                           FROM TEAMS)
ORDER BY LEAGUES.LID DESC;

/* Query 2 */
SELECT
  TID,
  COUNT(*) AS W_NUM,
  TEAM_NAME
FROM TEAMS
  LEFT JOIN LEAGUES L ON TEAMS.TID = L.CHAMPION_TID
GROUP BY TID, TEAM_NAME
HAVING COUNT(*) >= 2
ORDER BY W_NUM DESC;

/* Query 3 */
SELECT
  TID,
  TEAM_NAME,
  LEAGUE_NAME,
  SEASON
FROM LEAGUES
  LEFT JOIN TEAMS ON LEAGUES.CHAMPION_TID = TEAMS.TID
WHERE LEAGUES.YEAR IN (2017, 2018)
ORDER BY TEAMS.TID ASC;

/* Query 4 */
SELECT
  SPONSORS.SID,
  COALESCE(SP.S_COUNT, 0) AS S_COUNT,
  SPONSORS.SPONSOR_NAME
FROM SPONSORS
  LEFT JOIN (SELECT
               SID,
               COUNT(*) AS S_COUNT
             FROM SUPPORT
             GROUP BY SID) SP ON SPONSORS.SID = SP.SID
ORDER BY S_COUNT DESC;

/* Query 5 */
SELECT
  RID,
  FOOTBALL_RANKING,
  REGION_NAME
FROM REGIONS
WHERE RID IN (SELECT DISTINCT RID
              FROM LEAGUES
              GROUP BY RID, SEASON
              HAVING COUNT(*) >= 2)
ORDER BY FOOTBALL_RANKING ASC;

/* Query 6 */
SELECT
  SID,
  SPONSOR_NAME,
  MARKET_VALUE
FROM SPONSORS
WHERE MARKET_VALUE > 150.0 AND
      SID IN (SELECT SID
              FROM SUPPORT
              GROUP BY SID
              HAVING SUM(SPONSORSHIP) > 3.0
              INTERSECT
              SELECT SID
              FROM SUPPORT
                LEFT JOIN LEAGUES L ON SUPPORT.LID = L.LID
                LEFT JOIN REGIONS R ON L.RID = R.RID
              WHERE FOOTBALL_RANKING > 10)
ORDER BY SID ASC;

/* Query 7 */
SELECT
  SID,
  SPONSOR_NAME
FROM SPONSORS
WHERE SID IN (SELECT DISTINCT SID
              FROM SUPPORT
              GROUP BY SID
              HAVING COUNT(SUPPORT.LID) >= 2)
      AND
      SID NOT IN (SELECT DISTINCT SID
                  FROM SUPPORT
                    LEFT JOIN LEAGUES L ON SUPPORT.LID = L.LID
                    LEFT JOIN REGIONS R ON L.RID = R.RID
                  WHERE REGION_NAME = 'Japan')
ORDER BY SID DESC;

/* Query 8 */
SELECT DISTINCT *
FROM (
  SELECT
    R.RID,
    R.REGION_NAME
  FROM SUPPORT
    LEFT JOIN LEAGUES L ON SUPPORT.LID = L.LID
    LEFT JOIN REGIONS R ON L.RID = R.RID
  WHERE SID IN (SELECT SID
                FROM SUPPORT
                GROUP BY SID
                HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                                   FROM SUPPORT
                                   GROUP BY SID))
  ORDER BY R.RID DESC);